# Generated by Django 2.1.5 on 2019-02-06 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0002_auto_20190206_1218'),
    ]

    operations = [
        migrations.AddField(
            model_name='rule',
            name='rule_title',
            field=models.CharField(default='Seguridad de la información', max_length=100),
            preserve_default=False,
        ),
    ]
