# Generated by Django 2.1.5 on 2019-02-06 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0003_rule_rule_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='conflict_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='evidence',
            field=models.ImageField(blank=True, null=True, upload_to='evidences'),
        ),
    ]
